### PR TITLE
Different styling for contact form

### PR DESCRIPTION
**Pull request by DillonSimeone**
Getting my tiny pull requests practice in!

Contact form is made so the labels and the inputs displays in a row, and a bottom border is added to the h2 text above the form.

The contact form's style change in this one still isn't nice to look at yet, but it might be headed somewhere nice. 

Maybe for the h2 in #contact...
- Different font and color ?
- Yellow bottom border instead of grey bottom border?

### CODE REVIEW

**Comment by DillonSimeone** [comment]
image

**Comment by sudz123** [comment]
The header of the contact form looks weird in yellow, either the placement needs to be changed or the colour or both. Also, when you submitted #175  this somehow changed the scroll properties and now the home and about and contact buttons do not scroll as they used to. Could you look into that too and submit a new PR for that? Just see how it was before you submitted #175, should be easy.

**Comment by DillonSimeone** [comment]
I see what you're talking about, yeah, just have to adjust the script a bit to get it working good as it was before. 

The onclick script is trying to scroll the viewport to ids that don't exist anymore due to optimization made by #175, fixing now. Trying to make another tiny pull for that without having that to become a part of this pull.

**Comment by sudz123** [comment]
Yup, Also the dotted line looks nice, but all the other changes are kinda making the form unsymmetric. I guess keeping in mind the page theme, the current colour suits it. See if you can make slight modifications for this.

**Comment by DillonSimeone** [comment]
There we go!

image

**Comment by DillonSimeone** [comment]
image

Hightlight showing how centered the inputs are.

**Comment by sudz123** [comment]
Great!

**Comment by sudz123** [comment]
The `Don't be a stranger` thing has slightly bigger font size also font could be much better, have a go at it!

**Pull request merged**
