### PR TITLE
added Contributing.md

### PR DESCRIPTION
**Pull request by akshatah33**

### CODE REVIEW

**Comment by sudz123** [comment]
I'd suggest you add it according to #3 , looks better

**Comment by akshatah33** [comment]
I resolved [issue#2](https://github.com/sudz123/Happy_Hacking/issues/2)

**Comment by akshatah33** [comment]
Wait, will change my contributing.md too with bullet points.

**Comment by akshatah33** [comment]
Do you suggest any more changes?

**Comment by sudz123** [comment]
Everything looks great, could you move our names to Contributors.md which has already been added in #3 and also create a new PR which adds a link to my LinkedIn, addressing #13

**Comment by akshatah33** [comment]
Ok sure.

**Pull request merged**
