### PR TITLE
fix image in home.html

### PR DESCRIPTION
**Pull request by albebonv**
#70

### CODE REVIEW

**Comment by sudz123** [comment]
I do want the image to be smaller, but you have removed the scrolling constrictions.

**Comment by albebonv** [comment]
i have cropped all images at the same size and added a wrapper to prevent the image to be higher than the viewport

**Comment by albebonv** [comment]
@sudz123 i did not understand the problem with the images

**Comment by sudz123** [comment]
What you did was right, except when we were scrolling we could scroll beyond the header and footer if I merged your PR

**Comment by albebonv** [comment]
I do not see the problem, which browser do you use?

**Comment by sudz123** [comment]
I use chrome.

**Comment by sudz123** [comment]
Actually my bad. It's working, but do try to rebase your branch and then submit a PR. It makes my life easier.

**Pull request merged**
