### PR TITLE
Big clean up

### PR DESCRIPTION
**Pull request by DillonSimeone**
Noteworthy change: Halloween button fancy keyframe animation.

See #145 and #146

### CODE REVIEW

**Comment by sudz123** [comment]
The contact form needs some margin, what you have done with the contributors buttons is good, but the rest of the stuff is not aesthetic, or need some more tweaks before I can merge.

**Comment by sudz123** [comment]
Also you can push the image. So I expect another PR for that.

**Comment by DillonSimeone** [comment]
I think this merge is not going to be a good one. Try to merge, and if it's all messed up as heck, give me the merged .css and I should be able to do a much better job with that than Github's unexpectly bare-bonded merge thingy.

**Comment by DillonSimeone** [comment]
Sudz123, I do not have any way to push the image. When attempting to upload a new file into images/halloween, I get this from Github:

"Uploads are disabled.
File uploads require push access to this repository."

That dialog is why I asked you to grab the image at that URL in the file and push the image on your side.

**Comment by sudz123** [comment]
Umm, I think you need to add a new file to the local repo and then do a git add followed by a git commit just as adding some new code, anyways if this is not working I will add the image. However I'd prefer not merging this if it's in a bad shape. Since, finally this project is attaining some stability. What I would suggest is if re-doing all this through patches is too much of a pain simply submit one PR with all the linked changes(This is a special case, I'm making an exception). If it runs well on my local machine I will merge that one PR. You can work further on it then.

**Comment by DillonSimeone** [comment]
I see. So the issue with me being unable to push an image is that I'm using github through the browser instead of via Git Gui or the equivalent. I'll be trying that in a bit.

Indeed. Normally I would make a big single pull, via the local repo set-up. I wanted to familiarize myself with github through the browser, and didn't quite expect to make so much changes. I expected a few cute lines of code there and there, but... I was horrified by what was happening on the HTML and CSS font and got carried away.

**Comment by sudz123** [comment]
Alright so here is the deal, I tried to work things around but this is how the page would look after I merge your PR : 

screen shot 2018-10-05 at 9 25 53 pm
screen shot 2018-10-05 at 9 26 06 pm

I really think it would be a bad idea to merge this, unless I am building your code wrong locally :/

**Comment by DillonSimeone** [comment]
Nah, go ahead! I can redo the CSS witchery with very little effort on my part.

Halloween button is not animated with the halloween picture, and the title in the header isn't animated. That should take me minutes to fix.  I can stay awake for a bit longer and get all of this straightened out in like, ten minutes tops. 

I attempted to push the image from a local repo I made, but sadly, got this error:
"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."

I double checked, I'm signed in my account on my desktop git for sure.

**Comment by DillonSimeone** [comment]
Hmm. Now that I've thought about it for a bit, I'm taking the wrong approach here for sure.

#145 and #146 should be fine to merge. This... You're right, lets not merge this one. I'll do a more careful merge after sleeping.

**Comment by DillonSimeone** [comment]
All right. I'm up now. I'm focusing my efforts on getting my local repo to work with Github. So I can submit one big PR instead of three PRs. Sadly, I'm having more trouble with this than expected.

With Git Gui, I was able to make a local clone of Happy_Hacking, and confirmed that it's pointing to this repo using a HTTPS link.

With Git Gui, I did...

- Remote > Fetch From > Origin
- Add image to src/images/halloween/ dir
- Stage Changes, Commit note, Commit
- Merge > Merge Local, image is merged without any issues.
- Push

Error I'm getting with Git Gui:
'remote: Permission to sudz123/Happy_Hacking.git denied to DillonSimeone.
fatal: unable to access 'https://github.com/sudz123/Happy_Hacking.git/': The requested URL returned error: 403
Pushing to https://github.com/sudz123/Happy_Hacking.git'

I've tried making a new branch then pushing that, only to get the same error. 

As you can see here, 
https://stackoverflow.com/questions/22666828/no-pull-in-git-gui

What I did should had worked.

I attempted to use Git bash using this tutorial, https://yangsu.github.io/pull-request-tutorial/, and had the same degree of success as I did with Git Gui:

image

I'm reading documentations on this right now.

**Comment by DillonSimeone** [comment]
It appears that Git Bash is able to detect the difference between master and my current branch. I'm still getting the strange 403 issue.

image

**Comment by DillonSimeone** [comment]
I think I see the issue here. I need to make a fork of your project, then clone that locally and make my changes. Then a public pull request should be possible.

**Comment by DillonSimeone** [comment]
Eureka! I've got it!

See #164.

Most excellent. If not for the conflicts, I wouldn't had learned all of this. OK! I should be able to make a single PR for the HTML, CSS and JS in one go now!

**Comment by sudz123** [comment]
Great, I am happy that you have learnt your lesson :P . Since this repo is meant for new comers to get used to git and open sourcing, many contributors com up with the same questions. Get all your answers here through practice and once Hacktoberfest ends, put these skills to use in a good project. Happy Hacking 👯

**Comment by DillonSimeone** [comment]
Heck, yeah! I'm thankful for Hacktoberfest getting me to stop avoiding Github!

I just made a big PR, see #175. Closing this and #146 and #145.

**Pull request closed without merging**
