### PR TITLE
added Menu

### PR DESCRIPTION
**Pull request by nibiru2O12**
Added Menu on home page

### CODE REVIEW

**Comment by nibiru2O12** [comment]
initial image image is also set

**Comment by sudz123** [comment]
We need a time varying home page image, the Menu buttons don't look different, kindly change that. Also the image resolution is set for the whole page. Take a look at home.html code which has been updated.

**Comment by nibiru2O12** [comment]
ok will update it

**Comment by sudz123** [comment]
Great. Now think of adding links to the menu buttons

**Comment by nibiru2O12** [comment]
working on it.

**Comment by nibiru2O12** [comment]
https://github.com/sudz123/Happy_Hacking/pull/95#issue-220214750

**Pull request merged**
