### PR TITLE
Background Transition change

### PR DESCRIPTION
**Pull request by DillonSimeone**
I noticed that Firefox can't use transition with backgrounds. This is my alternative approach to make something that would work across all browsers. The values still need to be fiddled with a bit more to get it to be even better. 

Perhaps I could make it to appear that it's scrolling forever in one direction.

Image1, Image2, Image3, Image1 then snap back to the first image1 and keep on scrolling in one direction.

Firefox haven't implemented Background-Image transition, and appears to have no plan to do so.

https://bugzilla.mozilla.org/show_bug.cgi?id=546052

https://stackoverflow.com/questions/9483364/css3-background-image-transition

I also added all vendors' prefixes. (By a plugin, not by hand! That would be insane!)

### CODE REVIEW

**Comment by DillonSimeone** [comment]
FYI, the background-position values I threw in there was completely random. Barely any thought behind them. Dripping toes into the water to see if this direction appears worthwhile to head in, pretty much.

**Comment by sudz123** [comment]
Okay so I don't use firefox but Diptanshu does, so he will review this. For now do try to make the transitions a wee bit faster and also see if you can get them moving in one direction in this PR. Good going.

**Comment by diptanshu-sopho** [comment]
Good going, works on firefox too! But as @sudz123 pointed out, try to make the transitions a wee bit faster and in one direction.

**Comment by DillonSimeone** [comment]
@diptanshu-sopho 

I manged to get the images to scroll forever in one direction on my first attempt (And adjusted the speed) using just CSS3 magic. Man. Like, five years ago, when I was starting out, I couldn't imagine doing something like this with just CSS3... Would talk about doing it with JavaScript instead.

**Comment by diptanshu-sopho** [comment]
Scroll in one direction is okay, but only the first image is fully visible. Only 1/4th of second and third images is visible.

**Comment by DillonSimeone** [comment]
Ah, I didn't notice that because I was testing the output on split screen. Hmm. Defining an exact width and height for the background images instead of percentages will probably fix this.

**Comment by DillonSimeone** [comment]
It should be fixed now. How do it look on your side now, @diptanshu-sopho?

**Comment by diptanshu-sopho** [comment]
Good going man! Looks good.

**Pull request merged**
