### PR TITLE
Clean up and indenting

### PR DESCRIPTION
**Pull request by DillonSimeone**
Stylesheet and JavaScript is changed too. Making pulls for those now.

### CODE REVIEW

**Comment by sudz123** [comment]
Kindly rebase with master and take a look into the conflicts.

**Comment by sudz123** [comment]
Also checkout #150 that looks more aesthetic. Maybe you can add some of these changes to that.

**Comment by DillonSimeone** [comment]
Hmm. This is my first time with a conflict in github. I'm clicking random buttons right now.

**Comment by DillonSimeone** [comment]
All right, I think I've got it now. Onclick animated scroll was added to the nav in the header, and a h3 title was placed in the header too. That's all the changes that was made, I think.

**Comment by sudz123** [comment]
Okay I'll help you out here. So basically between the time when you cloned your branch to the time when you submitted your PR, some PRs got accepted and it changed the code. So for eg. here you can see that home.html got changed. This happens often when you are making changes to important files which are very frequently being developed. First save whatever changes you made in some other file out of the repo. I'll take a look into your new patch here, but I hope you have made your changes in accordance with the new site. Otherwise do a git pull for the updates take a look at the changes and then make suitable commits.

**Comment by sudz123** [comment]
I say remove the header, make sure the contact form has enough margin and there is a bounding box around it. Other smaller changes are fine for merging.

**Comment by DillonSimeone** [comment]
I agree, the hacking animation do belong on the top instead of the footer for sure. Nicer up there. 

I just examined #150 more closely, it appears that I only missed the hacking animation in the footer with my newbie merge. Removing the title from the footer now.

**Comment by DillonSimeone** [comment]
I am not sure what you're saying about the header. The h3 title should fit nicely in the header and be easier to read due to the single color background than it would be on the start pictures.

**Comment by DillonSimeone** [comment]
The sun is up, and I'm quickly becoming too tired to stay awake any longer. I should be back online in about seven to nine more hours. My red-eyed merging might have caused more bad merges than otherwise.

**Comment by sudz123** [comment]
Well. Your efforts have been valiant, I am trying to run all your changes locally. I'll try my best to merge it. sleep tight!

**Comment by DillonSimeone** [comment]
See #175

**Pull request closed without merging**
